[Service]
WorkingDirectory=/home/isucon/private_isu/webapp/python
ExecStart=
ExecStart=/home/isucon/private_isu/webapp/python/.venv/bin/gunicorn \
  --bind unix:/home/isucon/tmp/gunicorn.sock \
  --umask 007 \
  app:app
